### ISSUE TITLE
sources jar is missing

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#11]
Please could you add a sources.jar? We would like to have at least java doc.

It is very painfull to manually assign a git repo as source for your api artefact.
I thought about importing your repo as project and add the sources task by my self just to be able to add it to my local repository.

Kind Regards

**Comment by menion** [comment]
Hello Falco,
thanks for pointing on this issue. Please try latest recreated API version 0.3.2 where should javadoc & sources be or download it manually from [here](https://bintray.com/asammsoft/maven/locus-api-android/0.3.2#files/com%2Fasamm%2Flocus-api-android%2F0.3.2) (tab files). Thanks

**Comment by Falcosc** [comment]
Thank you.

I wonder why nobody did ask for this before. Maybe everybody thought: He is the Locus developer, there have to be a reason to not generate a sources profile. Probably we do something wrong, let’s just import the api project instead of asking him to generate a sources jar ;)
