### ISSUE TITLE
Incorrect call `ActionTools.displayLocusStoreItemDetail`

### ISSUE THREAD

**Issue by menion** [asamm/locus-api#17]
Call ends with 
`Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`.

Solution?
Attach correct flag that starts new task stack.

**Comment by afnyy** [comment]
I set up the project step by step according to the instructions, but there are always various problems, never succeeded. Can you publish the source code of Locus API Sample?

**Comment by menion** [comment]
Hello afnyy,
sorry for late response. 
Do you still have a problem with the setup of API? If so, please create a new issue with a problem(s) you deal with. Thanks.

**Comment by afnyy** [comment]
你好！
非常感谢您的回复。
经过一段时间的学习，我现在可以继承ComputeTrack服务来制作我需要的轨迹。我是一架小飞机的飞行员，Locus Map API提供的强大功能可以满足我的日常工作需求。但现在有一个问题，附件中的清单。我希望我们可以自定义所需的速度和时间计算结果。但似乎没有实现它的接口。我希望得到你的帮助。谢谢。





------------------ 原始邮件 ------------------
发件人: "Jiří M. aka Menion"<notifications@github.com>;
发送时间: 2019年8月20日(星期二) 晚上7:19
收件人: "asamm/locus-api"<locus-api@noreply.github.com>;
抄送: "北方"<afnyy@foxmail.com>;"Comment"<comment@noreply.github.com>;
主题：  Re：[asamm / locus-api]调用错误`ActionTools.displayLocusStoreItemDetail`（＃17）




您好afnyy，
 抱歉迟到的回复。
 您是否仍然遇到API设置问题？如果是这样，请创建一个新问题，解决您遇到的问题。谢谢。
  
- 
你收到这个是因为你发表了评论。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。
