### ISSUE TITLE
Get point by name not working

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#23]
If I  use this function in my own code, cursor is always null.

Then I did compile sample application and same issue there: https://github.com/Falcosc/locus-api/blob/911297c0753b6521c87711d6fc4bf43274fc7420/locus-api-android-sample/src/main/java/com/asamm/locus/api/sample/utils/SampleCalls.kt#L374

Always empty

But if I install sample application from play store, it does work fine.

My point name is "name" and play store example returns Id [1163]

But if I compile the sample with current android studio in debug mode without any modification, it won't work and alertdialog returns []

Did I need to change anything in android studio or is this not working on debug builds?

Kind regards
Falco

**Comment by Falcosc** [comment]
I did add some inline questions on the broken commit https://github.com/asamm/locus-api/commit/a9718b6860031d6e2348c6c4eaa641fdd7989cae

https://github.com/asamm/locus-api/commit/a9718b6860031d6e2348c6c4eaa641fdd7989cae#r34110655
https://github.com/asamm/locus-api/commit/a9718b6860031d6e2348c6c4eaa641fdd7989cae#r34110525

**Comment by menion** [comment]
Hello Falco,
thanks for the precise bug report and also the pull request that correctly fixed the mentioned problem.
Issue fixed in the new 0.3.17 version.
