### ISSUE TITLE
ActionDisplayPoints sendPacksFile - fileUri not everywhere optional

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#25]
In the implementing function the parameter fileUri is optional:
```
private fun sendPacksFile(action: String, ctx: Context, lv: LocusUtils.LocusVersion,
            data: List<PackPoints>, file: File, fileUri: Uri?, ....
```
(Line 261)

This method is called in line 105 and 240, but not defined as optional:
```
    fun sendPacksFile(ctx: Context, lv: LocusUtils.LocusVersion,
            data: List<PackPoints>, file: File, fileUri: Uri, extraAction: ExtraAction): Boolean {
        return sendPacksFile(LocusConst.ACTION_DISPLAY_DATA,
                ctx, lv, data, file, fileUri,
                extraAction == ExtraAction.IMPORT,
                extraAction == ExtraAction.CENTER)
    }
```
```
    fun sendPacksFileSilent(ctx: Context, lv: LocusUtils.LocusVersion,
            data: List<PackPoints>, file: File, fileUri: Uri, centerOnData: Boolean): Boolean {
        return sendPacksFile(LocusConst.ACTION_DISPLAY_DATA_SILENTLY,
                ctx, lv, data, file, fileUri,
                false, centerOnData)
    }
```

**Comment by menion** [comment]
Hello bekuno
good point and thanks for PR. I've made a few days ago some bigger changes in API structure (most of Locus API code moved to Kotlin + removed some deprecated fields), so PR was no longer able to merge. Anyway, changes applied manually in the latest 0.9.2 version.

If you will have time, you may give it a try and let me know if the [current implementation](https://github.com/asamm/locus-api/blob/master/locus-api-android/src/main/java/locus/api/android/ActionDisplayPoints.kt#L168) is correct.

Suggest to check system in `SampleCalls` class in samples.
