### ISSUE TITLE
Error in call lastIndexOf in class GeocachingAttribute

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#32]
I try to implement the attribute mapping from c:geo to locus, so you can see the cache in locus with attributes.
Therfore I need to use the secondary constructor `constructor(url: String) : this()` in the `class GeocachingAttribute()`.

If I understand the documentation right than the constructor needs to be annotated with `@JvmOverloads` to be accessible in java.
See https://kotlinlang.org/docs/java-to-kotlin-interop.html#overloads-generation .

I hope that this is the correct way.

**Comment by menion** [comment]
Hello bekuno,
`@JvmOverload` is not needed here, it is used for different use-case (creating multiple methods from calls with default parameters).

As I'm testing it, all three constructors are correctly available and visible to the public. May you please double check it? Thanks

![image](https://user-images.githubusercontent.com/1257075/108026665-139da280-7029-11eb-8838-0d582d6448c4.png)

**Comment by bekuno** [comment]
Hello Menion,
Thanks for the fast answer.
You are right, the problem is not in the moment of the parameter assignment to Geocaching Attribute.

It is in the parameter assignment in the constructor
`val imgName = url.substring(url.lastIndexOf("/" + 1), url.lastIndexOf("-"))` in `lastIndexOf("/" + 1)`
![grafik](https://user-images.githubusercontent.com/32555742/108119917-c65d1780-70a0-11eb-8d81-9882d15948d5.png)

I would say this should be 
`val imgName = url.substring(url.lastIndexOf("/") + 1, url.lastIndexOf("-"))`

**Comment by menion** [comment]
Thank you very much. What a stupid issue!
Fixed in **API version 0.9.27**.

**Comment by bekuno** [comment]
It is fine now.

Question from testing: Are some attributes not yet implemented in the current locus version (3.50.1)?
I miss all of the new added in locus-api, eg. the bonuscache attribute (bonus, 169).

**Comment by menion** [comment]
This is correct. They are already available in the [Beta version](https://forum.locusmap.eu/index.php?topic=7188.0) if you wanna test . Public version will be most probably available during the next 3 weeks.

**Comment by bekuno** [comment]
Works fine with the beta version.
Thanks for the great job.

**Comment by menion** [comment]
Perfekt!

No need to thank me. Carnero started work on the c:geo at the same time as Locus Map. No many apps survived 10+ and I also think it is a very nice and unique app = so great job as well ;).

Thanks also for integrating the new version of the Locus API. In case of any problems or missing content/features, feel free to open an issue here.
