### ISSUE TITLE
use of JCenter is deprecated

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#33]
The service of JCenter will be sunset.
 -  JCenter new package versions submission deadline through March 31st 2021
 -  repository will keep serving packages for 12 months until February 1st 2022

For details see 
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://developer.android.com/studio/build/jcenter-migration

**Comment by bekuno** [comment]
fixed in version 0.9.32
Thanks @menion

**Comment by menion** [comment]
It took some time but finally done. Uff.
