### ISSUE TITLE
revert the deletion of the value CACHE_SIZE_HUGE

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#35]
Please revert the deletion of the value CACHE_SIZE_HUGE.
This cache size is the comparable size from OpenCaching size 'xlarge'.
(see https://opencaching.pl/okapi/services/caches/geocache.html 'size2')

**Comment by menion** [comment]
Hi,
thanks for this. I was curious why "huge" size was in the API. And here is the reason. In 0.9.34, it is added back. In the app will be "size legend" modified for opencaching and geocaching caches.
