### ISSUE TITLE
Why does the sample app Query permission not match to API package list?

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#36]
https://github.com/asamm/locus-api/blob/4759711ac504992e937344ba8171cb857ae6c0eb/locus-api-android-sample/src/main/AndroidManifest.xml#L11-L16

https://github.com/asamm/locus-api/blob/4759711ac504992e937344ba8171cb857ae6c0eb/locus-api-android/src/main/java/locus/api/android/utils/LocusUtils.kt#L36-L44

**Comment by menion** [comment]
Hi Falco,
thanks. This was an unfinished task that I was just testing. In the recent [commit](https://github.com/asamm/locus-api/commit/a1f278b5669841124ccb825753b4029c780f199a), queries are now directly in Locus API - Android module and test confirmed that it works now correctly for apps targeting Android 11.

**Comment by Falcosc** [comment]
Next week I would take a 0.9.36 release for my Android 11 Update and Library upgrade release.
