### ISSUE TITLE
Api does not work, when targetting android version 30

### ISSUE THREAD

**Issue by sir-gawain** [asamm/locus-api#38]
When targetting android sdk 30 the API will fail. 
This is because pm.getPackageInfo() gets filtered by default.

This can be solved by adding 

```xml
<queries>
        <package android:name="menion.android.locus"/>
        <package android:name="menion.android.locus.free.amazon"/>
        <package android:name="menion.android.locus.free.samsung"/>
        <package android:name="menion.android.locus.pro"/>
        <package android:name="menion.android.locus.pro.amazon"/>
        <package android:name="menion.android.locus.pro.asamm"/>
        <package android:name="menion.android.locus.pro.computerBild"/>
</queries>
```

into the manifest.

**Comment by menion** [comment]
Hi,
are you using latest Locus API version? Because there already exists query based on the "intent" that should solve this issue: https://github.com/asamm/locus-api/blob/5d24ee54368fed56778feb6c695f5f58435acd67/locus-api-android/src/main/AndroidManifest.xml#L5

**Comment by sir-gawain** [comment]
I think so:

implementation 'com.asamm:locus-api-android:0.9.35'

the addon was correctly listed in the locus view of geocaches, but calling it resulted in "wrong intent".
It started working after adding above code to my apps manifest.xml

I only took a look into the demo applicaton's manifest, not at the one of the library itself.

**Comment by Falcosc** [comment]
You need to release this bugfix.

**Comment by menion** [comment]
Heh, thanks Falco, this is a very good point. VErsion 0.9.36 will be available within a few minutes. Thanks!

**Comment by sir-gawain** [comment]
Updated to the new version and now it works without my additions again. Thx!
