### ISSUE TITLE
Parallel Useage of Locus Map Classic and Locus Map 4 - which is in foreground?

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#39]
I don't know why, but every week more users with multiple installed versions complain about having trouble with the API because `getActiveVersion` did select the wrong version.

I would like to implement a reminder for all users who have installed both versions.
With `getVersions` and `isRunning` I know which users should get the reminder to select the correct version.

If both versions are running, how can we detect which of them is in the foreground? It would be ok if the function is expensive because I remind only once per session. If the command target package matches the foreground application user did everything right and don't need a reminder. But if the command target package miss matches the application and user did not specifically define a target package, user should get a reminder to set the target package.

How can we detect which of both apps are in foreground?
It would also be ok if you don't add the foreground check to the API. I just want to know which method is the most stable to detect which of both versions is currently used. (Both versions are running because users are lazy and don't close old applications)

**Comment by menion** [comment]
Hello Falco,
I'll try to help by describing what exactly these parameters means.

I've updated javadocs so hope, it will be clear now.
```
    /**
     * Flag if Locus is currently running. This means if app has valid instance of
     * the "Main activity" screen (core screen with the map).
     */
    var isRunning: Boolean = false
    /**
     * Time of last activity (in ms). This parameter is refreshed in the moment, 'onResume()' of
     * the main activity screen is called.
     */
    var lastActive: Long = 0L
```

Be aware that the object is refreshed once per minute.
Anyway using of the `lastActive` value may help here.

**Comment by Falcosc** [comment]
lastActive is good enough if this is refreshed on each `onResume` call.

It does work great so far, I can open both apps and the last selected one can be detected by last active.

But what do you mean with 
> Be aware that the object is refreshed once per minute.

**Comment by menion** [comment]
Oki, perfect.
I wanted to wrote that the app internally caches this object and it is refreshed once per minute - the app does not always generate the fresh object for every request.

Anyway in the next version will be this behavior updated, so you will get always the latest data.
