### ISSUE TITLE
Sensor Speed vs GPS Speed

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#41]
I did start to copy your java doc into my tasker plugin as field descriptions. For me, it is not clear which speed variable does represent which speed value.

This does sound like GPS speed:
https://github.com/asamm/locus-api/blob/4ae271c7660b304a64dff4292cf08bb19fe9cd79/locus-api-core/src/main/java/locus/api/objects/extra/Location.kt#L344-L347

But on the other hand this description does mention the "fix"
https://github.com/asamm/locus-api/blob/4ae271c7660b304a64dff4292cf08bb19fe9cd79/locus-api-core/src/main/java/locus/api/objects/extra/Location.kt#L578-L580

So now I'm not sure which of them is the Bike Speed Sensor and which is the NMEA speed. Or do you calculate speed and ignore the NMEA reported value?

**Comment by menion** [comment]
Hi Falco,
I've just updated javadoc in the `Location` object, thanks.

Names are correct, javadoc were not.
`speed`- speed received by the system hardware GPS (or external Bluetooth - NMEA)
`sensorSpeed` - really speed only from the connected sensors
