### ISSUE TITLE
Documentation for Map Zoom values

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#42]
According to the last update: https://github.com/asamm/locus-api/issues/37

We got the following range: `[0-24]` where 0 is the whole world.

How does it work with the new action "map_move_zoom"?
- it does not have +/- options
- value range of new action `[1;22]` does not match to the old command 
- why is the default value of map_move_zoom `0`?

How does map_move_zoom work if you want to avoid zooming and define a move only task like "move diagonal"?
According to the old documentation, it would zoom to "whole world" because non defined zoom value defaults to `0` and 0 means whole world.

I don't understand the use case of zooming and moving at the same time, so I am not sure why this API should deal with the hassle of "how to define a movement without zoom". Maybe it is more easy to exclude zooming and add the animate command to the old map zoom?

**Comment by menion** [comment]
You force me to make this new action perfect, thanks 😉 

Update: https://github.com/asamm/locus-api/wiki/Action-tasks-(Broadcasts)#map_move_zoom

Firstly, thanks for the good points. Zoom level updated in both cases to [0;24] ('0' value did not work in current version as well), Default is now set to a negative value which means = no zoom.

Moving and zooming is extremely useful if you want to for example display any area or any point on the map. You may then know that zoom X is optional so with this new update method, you may center to this point and zoom to the ideal zoom level.

Check it if it makes sense now, thanks.

**Comment by Falcosc** [comment]
> Moving and zooming is extremely useful if you want to for example display any area or any point on the map. You may then know that zoom X is optional so with this new update method, you may center to this point and zoom to the ideal zoom level.

But we can only move by %,dp,px. is there a method to calculate where to scroll if you have lon/lat?

Edit: ok you already solved this question, you added lon/lat. Now zoom makes sense.
