### ISSUE TITLE
How to find the via point in track?

### ISSUE THREAD

**Issue by Falcosc** [asamm/locus-api#43]
Is there a way to find the via point in the track?

We still don't have remaining elevation, so I have an extended update container which does check at which position in track the current navpoint is located.

If I found the point, I can roughly calculate the remaining elevation to the navigation target.

I would like to extend it by  roughly calculate the remaining elevation to the next via point if you don't plan to implement  remaining elevation as dashboard value for classic.

I did check if I can do the same "find nav point in track point list" where I compare the location with point locations based on this data 
https://github.com/asamm/locus-api/blob/efe49d80d25dece686d4d25f35bf49083c477b62/locus-api-android/src/main/java/locus/api/android/features/periodicUpdates/UpdateContainer.kt#L518

But the new via point doesn't have a location and I am not sure if we can find via points in the track object: https://github.com/asamm/locus-api/blob/82d0b51472dc71420df0fea23280cb34dc97ee8c/locus-api-core/src/main/java/locus/api/objects/geoData/Track.kt

By the way, I could use equal operator for comparing navigation track floating point values with the `guideNavPoint1Loc` field which did speed up the code because I guess you did share the same floating point base and exponent across guideNavPoint1Loc and Track.points :)
https://github.com/asamm/locus-api/blob/82d0b51472dc71420df0fea23280cb34dc97ee8c/locus-api-core/src/main/java/locus/api/objects/geoData/Track.kt#L145

**Comment by Falcosc** [comment]
I don't even know if it would make sense to calculate elevation at all for auto-routing tracks because I don't know if you do extend online routing or offline routing results with altitude values for each point between current location and next via point.

I have used elevation calculation only for manually planed tracks with high-resolution altitude values.

**Comment by Falcosc** [comment]
@menion 
Would be nice if there is a way to know where the next via point in the track is to calculate the remaining elevation. Did I miss a function to detect it in the track point list?

**Comment by menion** [comment]
Hello Falco, I do not think, there is an easy way to do it. Only what comes to my mind is to grab the whole track based on the `guidanceTargetID` value, search for the nearest trackpoint based on the current user location and then compute the remaining elevation as you need.

**Comment by Falcosc** [comment]
That is what I am currently successfully doing.
But even more simple. The result is good enough by using the next guide point as "current position" because guideNavPoint1Loc does use the same double value like the track data, I can even compare the memory with a simple equal sign and don't need rounded floating-point comparisons.

So, it does already work for remaining elevation to target. That was not the question :)


But now I would like to extend by "remaining elevation to via point"

My question is: Is there a way to find via points in the track?

**Comment by menion** [comment]
Perfect.
Sure it is. You may grab all `waypoints` attached to the track and check every `wpt.parameterRteAction == PointRteAction.PASS_PLACE`.

**Comment by Falcosc** [comment]
Cool, thank you

just to confirm, they are stored here, right?
https://github.com/asamm/locus-api/blob/82d0b51472dc71420df0fea23280cb34dc97ee8c/locus-api-core/src/main/java/locus/api/objects/geoData/Track.kt#L154

**Comment by menion** [comment]
Yes, `waypoints` container is correct place.
