### ISSUE TITLE
feature request : return with one click

### ISSUE THREAD

**Issue by ajay-gh** [asamm/locus-api#47]
In a number of use cases one has to go deep down through several layers of menus before 
a) making or undoing a temporary change (e.g. in settings), or 
b) before finding some information (e.g. on a point or track).
Next you want to go back to where you were before (e.g. route planning). This "going back" does currently (LM Classic 3.64.0) require you to do again some 3-5 point/click commands (often back arrow on the top left).

It would be great if one had just one "all the way back" button, ideally to the funciton last invoked, otherwise at least to the map screen. Great time saver, and helps you maintain your patience with little screens on Android. 
BTW, Tom-Tom navigators have had this button for a long time - proof that it is useful.

**Comment by menion** [comment]
Hello,
this is more an idea for existing Locus Map/Locus Classic apps, that belong to our help desk: https://help.locusmap.eu , than to this repository related to Locus API itself. Thanks for understanding.
