### ISSUE TITLE
Lomap Lv4 issue

### ISSUE THREAD

**Issue by ajay-gh** [asamm/locus-api#49]
I am using multiple Lomaps of France (Lv3) which I do not plan to update, switching between them (manually or when you move from one map area to another) has never caused problems. The setting in LM Classic 3.68 under settings > maps > offline maps > has always been "automatic map loading". 
Recently I purchased two more Lomaps shown in the maps list as Lv4. And there are two issues with that, which I report here as a locus-api bug.

1) the map loading with these new maps is very slow (compared to earlier Lv3 maps)
2) the automatic map switching (when going to or coming from a neighboring Lv3 map) does not work.

I assume it is a bug, but if this is the wrong place to report it here. please DO NOT just close the issue, but let me know where to report it.

**Comment by menion** [comment]
Hello,
please post issues related to the Locus Map application to its public support site here: https://help.locusmap.eu/ . This GitHub repository is dedicated to the developer API for the Locus Map app, not a "common" users issues. Thanks for understanding.

**Comment by ajay-gh** [comment]
Sure, will do !

**Comment by ajay-gh** [comment]
Could you please leave my 3 posts on for 6 hours, so I can copy the text and don't have to write it up all again?
