### ISSUE TITLE
error with Point class after change to version 0.9.50

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#52]
Whenn using version 0.9.50 of the locus-api we get error like
~~~
14:58:50  /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java:256: error: cannot find symbol
14:58:50          p.setParameterDescription(
14:58:50           ^
14:58:50    symbol:   method setParameterDescription(String)
14:58:50    location: variable p of type Point
~~~

See https://github.com/cgeo/cgeo/pull/13985
(https://ci.cgeo.org/job/cgeo-CI_PR-build/5294/console)

I know, that this is result of the 
`- separating extensions to Point & Track into separate helper class`

But I found no way to access the method in the helper class.
Please check it and/or guide me how to access now this method.

**Comment by menion** [comment]
Hello @bekuno , sorry for the breaking change.

Parameters, for simplicity, were moved to the separate class as an [extension function](https://github.com/asamm/locus-api/blob/2fbd81aba8d6ff0a3872c4c0b0f79a6ed15e43d3/locus-api-core/src/main/java/locus/api/objects/geoData/GeoDataHelper.kt#L67).

Hope this is what you are looking for.

**Comment by bekuno** [comment]
@menion I found this class, but no way to use with java.

In c:geo we have (see https://github.com/cgeo/cgeo/blob/14c549a62cc6a905d348e7683f4810476a839f96/main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java#L255-L256)
~~~
        final Point p = new Point(waypoint.getName(), loc);
        p.setParameterDescription(
~~~

Do you have an idea, how to change the second line?

**Comment by menion** [comment]
Sure,
this one should work as a fallback from Java to Kotlin source

```
GeoDataHelperKt.setParameterDescription(p, "description");
```

**Comment by bekuno** [comment]
@menion 
Thanks. Now I had time to finish - see https://github.com/cgeo/cgeo/pull/14562.
