### ISSUE TITLE
GeocachingData.CACHE_SIZE_VIRTUAL - missing implementation

### ISSUE THREAD

**Issue by bekuno** [asamm/locus-api#54]
With commit [a9398e0](https://github.com/asamm/locus-api/commit/a9398e0a180c9141f34723286e7a0e627649f2b0) the `val CACHE_SIZE_VIRTUAL` was introduced.
Many thanks.

But there is no implementation in https://github.com/asamm/locus-api/blob/81c24658228f5eaf8182671102fbec3f13305ff0/locus-api-core/src/main/java/locus/api/objects/geocaching/GeocachingData.kt#L294 and https://github.com/asamm/locus-api/blob/81c24658228f5eaf8182671102fbec3f13305ff0/locus-api-core/src/main/java/locus/api/objects/geocaching/GeocachingData.kt#L308 .

We use the method in c:geo https://github.com/cgeo/cgeo/blob/17fc62275e1599437c514833c01d17b4a235c078/main/src/main/java/cgeo/geocaching/apps/AbstractLocusApp.java#L182 .

**Comment by menion** [comment]
Thanks, fixed.

Version 0.9.55 will be available within an hour.
