### ISSUE TITLE
Switch map in single click

### ISSUE THREAD

**Issue by erva** [asamm/locus-api#6]
I'd like to have buttons on dashboard (button per map) for more quick map switch. Is there any api for it?

**Comment by menion** [comment]
Good day erva,
Locus API currently does not provide any access to available maps and also no option how to manipulate with maps visible on the screen. This maybe more belongs to help.locusmap.eu system where we collect ideas for app itself. Anyway I have to say that current "Quick map switch" should be good enough solution for quick change of map in visible area. Thanks for understanding.
