### ISSUE TITLE
getMapPreview() dops an exception

### ISSUE THREAD

**Issue by mzperxx** [asamm/locus-api#7]
ActionTools::getMapPreview() drops an exception at line "byte[] data = cursor.getBlob(1);" in the second round when i=1.

This code work for me (but not sure that correct):

			for (int i = 0; i < cursor.getCount(); i++) {
				cursor.moveToPosition(i);
				//String key = new String(cursor.getBlob(0));

				if (cursor.getType(1) == FIELD_TYPE_BLOB)
					img = cursor.getBlob(1);
				else
					if (cursor.getType(1) == FIELD_TYPE_INTEGER)
						notYetLoadedTiles = cursor.getInt(1);

				/*if (key.equals(LocusConst.VALUE_MAP_PREVIEW)) {
					img = data;
				} else if (key.equals(LocusConst.VALUE_MAP_PREVIEW_MISSING_TILES)) {
					notYetLoadedTiles = Utils.parseInt(new String(data));
				}*/
			}

**Comment by menion** [comment]
Thanks for report. Issue fixed in new 0.2.12 version.
