### ISSUE TITLE
LocusUtils.getAvailableVersions(...) returns empty list on Android 8.0 when any Instant App is installed

### ISSUE THREAD

**Issue by arcao** [asamm/locus-api#9]
This is known bug reported in Google issue tracker: https://issuetracker.google.com/issues/73289329

Should it be possible to rewrite this method to use `PackageManager.getApplicationInfo(<pkg>,0)` instead of searching specific packages in all installed packages via `PackageManager.getInstalledApplications(0)` ?

**Comment by menion** [comment]
Thanks, should be fixed now. If issue happens on your own device, please check it with version 0.2.21 if it works as expected.
